name: Bug report
description: "Create a report to help TaterLib improve \n **Please Note, Mixin errors containing** `org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: Unsupported class file major version` **are not fatal can be ignored.**"
labels: 'bug'
body:
  - type: textarea
    attributes:
      label: Debug Information
      description: Please run `/taterlib fulldump` and send the resulting link, **or** attach the `logs/taterlib-fulldump.json` file to this report.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Description of behavior
      description: A clear and concise description of what the bug is, including what you expected to happen and what actually happened.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Reproduction Steps
      value: |
        Steps to reproduce the behavior:
        1. Use above version of TaterLib and server software with mod "someMod"
        2. Run the server/start a world
        3. Something happens, error occurs, etc.
      render: markdown
    validations:
      required: true
  - type: textarea
    attributes:
      label: TaterLib Configuration
      description: Include your `taterlib.conf` file (omit sensitive information)
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the problem here (e.g. screenshots, clips, etc.)
    validations:
      required: false
